### ISSUE TITLE
Feature: CycleFreeFluxes

### ISSUE THREAD

**Issue by stelmo** [COBREXA/COBREXA.jl#29]
https://academic.oup.com/bioinformatics/article/31/13/2159/195895

**Comment by exaexa** [comment]
implementation hint: try to re-use as much of the parsimonious tooling as possible (maybe we should rename those to something like 2stage or postprocessing or so)

**Comment by exaexa** [comment]
@stelmo hey this is actually "just" the linear parsimonious FBA but with extra boudns on the exchanges, right?

BUT since the exchanges in the FBA are kinda free-floating, the normal linear parsimonious FBA would basically provide a compatible and correct CFF solution as well, right?
