### ISSUE TITLE
Feature: enzyme constrained FVA function

### ISSUE THREAD

**Issue by HettieC** [COBREXA/COBREXA.jl#67]
Hello!

It would be very useful to have enzyme constrained flux variability analysis as part of the package.

Hettie

**Comment by exaexa** [comment]
Hi,

you can run it by running `enzyme_constrained_flux_balance_constraints` instead of the `..._analysis`, and then directly run a `constraint_variability` on the tree you get from the first function.

Will that work?
-mk

**Comment by exaexa** [comment]
(I'll add a doc example for that)
